version: '3'

services:
  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=finagle_postgres_test
    volumes:
      - ./src/test/resources/extensions.sql:/docker-entrypoint-initdb.d/init.sql
